Make the guid options (-g) more flexible
Now it detects whether a format string is an absolute URI or
relative. As a special case, if the argument is ‘omit’ then the guid
element is not printed at all.

The logic is a bit confusing so this might need some cleaning up.

diff --git a/bin/pandoc-rss b/bin/pandoc-rss
--- a/bin/pandoc-rss
+++ b/bin/pandoc-rss
@@ -116,7 +116,8 @@ while getopts T:L:D:W:C:d:g:hp name
 do
     case "$name" in
     T)  channel_title=$OPTARG ;;
-    L)  channel_link=$OPTARG ;;
+    L)  channel_link=${OPTARG%/}
+	guid_format=${guid_format-$channel_link/%s.html};;
     D)  channel_description=$OPTARG ;;
     W)  channel_webmaster=$OPTARG ;;
     C)  channel_copyright=$OPTARG ;;
@@ -128,7 +129,15 @@ do
 	    exit 1
 	esac
 	;;
-    g)  guid_format=$OPTARG ;;
+    g)  case $OPTARG in
+	    omit)  guid_format= ;;
+	    *://*) guid_format=$OPTARG ;;
+	    /*%s*) guid_format=$channel_link/${OPTARG#/} ;;
+	    *%s*)  guid_format=$channel_link/$OPTARG ;;
+	    *) >&2 printf 'Invalid arg ‘%s’ for -%s option\n' "$OPTARG" "$name"
+	       exit 1
+	esac
+	;;
     h)  >&2 printf 'Usage: %s [OPTIONS] [FILE]...\n' "${0##*/}"; exit ;;
     p)  guid_is_perma_link=false ;;
     esac
