Implement -d|--description-source option

diff --git a/bin/pandoc-rss b/bin/pandoc-rss
--- a/bin/pandoc-rss
+++ b/bin/pandoc-rss
@@ -2,7 +2,7 @@
 
 usage ()
 {
-    >&2 printf 'Usage: %s [OPTIONS] FILE...\n' "${0##*/}"
+    >&2 printf 'Usage: %s [OPTIONS] [FILE]...\n' "${0##*/}"
 }
 
 get_metadata_value ()
@@ -26,7 +26,7 @@ get_permalink ()
     shift
     filename=${input_file##*/}
     basename=${filename%.*}
-    permalink=$(printf "$permalink_format" "$basename")
+    printf "$permalink_format" "$basename"
 }
 
 get_date ()
@@ -46,25 +46,36 @@ generate_feed_item ()
 
     if permalink=$(get_permalink "$input_file")
     then
-	set -- -V "permalink:$permalink"
+	set -- -V "permalink:$permalink" "$@"
     fi
 
     if date=$(get_date "$input_file")
     then
-	set -- -V "date:$date"
+	set -- -V "date:$date" "$@"
     fi
-    
-    pandoc --template="$templates_dir/item.xml" "$@" "$input_file"
+
+    pandoc --template="$item_template" "$@" "$input_file"
 }
 
 while true
 do
     case "$1" in
-    -f|--permalink-format)
+    -d|--description-source)
+	description_source=${2-}
+	case $description_source in
+	body|description|subtitle|abstract|none) ;;
+        *) >&2 printf 'Invalid description source ‘%s’\n' "$description_source"
+	   >&2 echo 'Valid sources: body, description, subtitle, abstract, none'
+	   exit 1
+	esac
+	shift 2
+	;;
+    -p|--permalink-format)
 	permalink_format=${2-}
 	case $permalink_format in
 	    *%s*) ;;
-	    *) >&2 echo 'Permalink format string must contain ‘%s’'; exit 1
+	    *) >&2 echo 'Permalink format string must contain ‘%s’'
+	       exit 1
 	esac
 	shift 2
 	;;
@@ -77,7 +88,7 @@ do
 	break
 	;;
     -*)
-	>&2 printf 'No such option ‘%s’' "$1"
+	>&2 printf 'No such option ‘%s’\n' "$1"
 	exit 1
 	;;
     *)
@@ -87,6 +98,8 @@ done
 
 share=${0%/*}/../share/pandoc-rss
 templates_dir=$share/data/templates
+
+item_template="$templates_dir/item-with-${description_source-body}.xml"
 
 for input_file do
     generate_feed_item "$input_file"
